device: cuda

node_num: 2460406
feat_dim: 100
class_num: 38

trainset_size: 0
valset_size: 0
testset_size: 0

layer_num: 2
layer_output_dim: [256, 256]
learning_rate: 0.01
batch_size: 1024
layer_train_batch: [30, 50]

bptt_step: 5
meta_learning_rate: 1
