device: cuda

node_num: 56944
feat_dim: 50
class_num: 121

trainset_size: 152410
valset_size: 23699
testset_size: 55334

layer_num: 4
layer_output_dim: [512, 512, 512, 512]
learning_rate: 0.001
batch_size: 512
layer_train_batch: [60, 60, 80, 100]

bptt_step: 5
meta_learning_rate: 1
