device: cuda

node_num: 232965
feat_dim: 602
class_num: 41

trainset_size: 152410
valset_size: 23699
testset_size: 55334

layer_num: 2
layer_output_dim: [512, 256]
learning_rate: 0.0005
batch_size: 256
layer_train_batch: [10, 10]

bptt_step: 5
meta_learning_rate: 1
